export enum EventType {
  LIKE_POST = "LIKE_POST",
  LIKE_COMMENT = "LIKE_COMMENT",
  SHARE_POST = "SHARE_POST",
  COMMENT_POST = "COMMENT_POST",
  SEND_MESSAGE = "SEND_MESSAGE",
  ACCEPTED_FRIEND_REQUEST = "ACCEPTED_FRIEND_REQUEST",
  PENDING_FRIEND_REQUEST = "PENDING_FRIEND_REQUEST",
}
